apiVersion: v1
kind: Namespace
metadata:
  name: angular-project-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
  namespace: angular-project-ns
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: angularapp
  template:
    metadata:
      labels:
        app: angularapp
    spec:
      containers:
        - name: angular-app-container
          image: agpocacr.azurecr.io/dotnetdockerfile:#{Build.BuildId}#
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc
  namespace: angular-project-ns
  labels:
    service: angular-app-svc
spec:
  type: LoadBalancer
  selector:
    app: angularapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
